apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-app
  namespace: default
spec:
  url: https://github.com/LolkeeN/flux-solo-practice-application
  ref:
    branch: master
